[vcpkg] Improve error reporting for vcpkg_abi_info.txt copy failure. (#15871)
In build https://dev.azure.com/vcpkg/public/_build/results?buildId=48398

we are getting output like:

```
Error: Building package v-hacd:x64-windows-static failed with: BUILD_FAILED
Elapsed time for package v-hacd:x64-windows-static: 4.156 s
Starting package 1396/1464: v8:x64-windows-static
Building package v8[core]:x64-windows-static...
-- Using msys root at D:/downloads/tools/msys2/969c0913b9df89e1
-- Fetching https://chromium.googlesource.com/v8/v8.git...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: C:/agent/externals/git/cmd/git.exe fetch https://chromium.googlesource.com/v8/v8.git 7565e93eb72cea4268028fc20186d415c22b1cff --depth 1 -n
    Working Directory: D:/downloads/git-tmp
    Error code: 128
    See logs for more information:
      D:\buildtrees\v8\git-fetch-x64-windows-static-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:91 (vcpkg_execute_required_process)
  ports/v8/portfile.cmake:71 (vcpkg_from_git)
  scripts/ports.cmake:128 (include)

Could not copy into file: D:\packages\v8_x64-windows-static\share\v8\vcpkg_abi_info.txt
```

but aren't printing the reason for the copy failure. Added printing of that reason.